export const ARTICLE_LIST_REQUEST = "ARTICLE_LIST_REQUEST";
export const ARTICLE_LIST_SUCCESS = "ARTICLE_LIST_SUCCESS";
export const ARTICLE_LIST_FAIL = "ARTICLE_LIST_FAIL";

export const ARTICLE_CREATE_REQUEST = "ARTICLE_CREATE_REQUEST";
export const ARTICLE_CREATE_SUCCESS = "ARTICLE_CREATE_SUCCESS";
export const ARTICLE_CREATE_FAIL = "ARTICLE_CREATE_FAIL";
export const ARTICLE_CLEAR_CREATE_REQUEST = "ARTICLE_CLEAR_CREATE_REQUEST";

export const ARTICLE_UPDATE_FAV_REQUEST = "ARTICLE_UPDATE_FAV_REQUEST";
export const ARTICLE_UPDATE_FAV_SUCCESS = "ARTICLE_UPDATE_FAV_SUCCESS";
export const ARTICLE_UPDATE_FAV_FAIL = "ARTICLE_UPDATE_FAV_FAIL";
export const ARTICLE_CLEAR_UPDATE_REQUEST = "ARTICLE_CLEAR_UPDATE_REQUEST";
